### PR TITLE
ConstraintDual for quadratic constraints

### LINKED ISSUE #171: Acessing constraint dual value
I have the same test optimization model in GAMS and Julia.

GAMS using Ipopt calculates dual values of constraints normally and in Julia I get error:
"ArgumentError: ModelLike of type Ipopt.Optimizer does not support accessing the attribute MathOptInterface.ConstraintDual(1)"

### PR DESCRIPTION
**Pull request by mlubin**
Fixes #171 

However, I'm hesitant to merge before we have an MOI convention for the sign of the duals and tests.
@schepy

### CODE REVIEW

File: src/MOI_wrapper.jl [hunk 1]
```diff
@@ -907,41 +907,40 @@ function MOI.get(model::Optimizer, ::MOI.ConstraintPrimal,
...
-    if model.inner === nothing
-        error("ConstraintDual not available.")
+macro define_constraint_dual(function_type, set_type, prefix)
+    constraint_array = Symbol(string(prefix) * "_constraints")
+    offset_function = Symbol(string(prefix) * "_offset")
+    quote
+        function MOI.get(model::Optimizer, ::MOI.ConstraintDual,
+                         ci::MOI.ConstraintIndex{$function_type, $set_type})
+            if model.inner === nothing
+                error("ConstraintDual not available.")
```
Comment (blegat) [inline src/MOI_wrapper.jl]: Why no throw `MOI.OptimizeNotCalled()` ?

File: src/MOI_wrapper.jl [hunk 2]
```diff
@@ -907,41 +907,40 @@ function MOI.get(model::Optimizer, ::MOI.ConstraintPrimal,
...
+            end
+            if !(1 <= ci.value <= length(model.$(constraint_array)))
+                error("Invalid constraint index ", ci.value)
```
Comment (blegat) [inline src/MOI_wrapper.jl]: Why not throw `MOI.InvalidIndex`, even better is call `MOI.throw_is_not_valid` to reuse `MOI.is_valid`

File: src/MOI_wrapper.jl (hunk 1 above)
Comment (blegat) [reply src/MOI_wrapper.jl]: Moving to issue to https://github.com/JuliaOpt/Ipopt.jl/issues/174

File: src/MOI_wrapper.jl (hunk 2 above)
Comment (blegat) [reply src/MOI_wrapper.jl]: Moving it to https://github.com/JuliaOpt/Ipopt.jl/issues/175
